env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - import
reportUnusedDisableDirectives: true
rules:
  "@typescript-eslint/ban-ts-comment":
    - warn
  "@typescript-eslint/no-non-null-assertion":
    - off
  "@typescript-eslint/ban-types":
    - off
  "@typescript-eslint/no-namespace":
    - off
  no-inner-declarations:
    - off
  import/order:
    - error
    - alphabetize:
        order: asc
        caseInsensitive: true
  sort-imports:
    - error
    - ignoreDeclarationSort: true
      ignoreCase: true
  quotes:
    - error
    - double
    - avoidEscape: true
  eqeqeq:
    - error
  prefer-const:
    - error
    - destructuring: all
overrides:
  - files:
      - "**/*.js"
    rules:
      "@typescript-eslint/no-var-requires":
        - "off"
  - files:
      - "test/**/*.spec.ts"
    plugins:
      - jest
      - jest-extended
    extends:
      - plugin:jest/recommended
      - plugin:jest/style
      - plugin:jest-extended/recommended
settings:
  import/parsers:
    "@typescript-eslint/parser":
      - .ts
      - .tsx
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: "./tsconfig.json"
